/*
* Author: Tyler
* Contributors:
* Last Modified: 09/16/2026
* Summary: This is the base scriptable object from which every scriptable object should derive
* To Do:   Add more functions as needed.
*/

using NaughtyAttributes;
using UnityEngine;

public class BaseScriptableObject : ScriptableObject
{
    [HorizontalLine(4, EColor.Green)]
    [Header("Tooltip Settings")]
    [Tooltip("Turn on if you want the tooltip service to try to autogenerate a tooltip. " +
        "\nShould probably usually be on, but it might generate weird sometimes.")]

    public bool UseAutoGeneratedTooltip = true;

    [Tooltip("Turn on if you want to write a tooltip yourself. If both this and autogenerate tooltips are on, " +
        "\nit'll generate then place the written one below.")]
    public bool UsePresetTooltip = false;

    [ShowIf(nameof(UsePresetTooltip))]
    [Tooltip("The text of the tooltip you want it to have. " +
        "Uses rich text so you can do stuff like <color=red></color>. " +
        "Google unity rich text if you want to see your options.")]

    public string PresetTooltip = string.Empty;


    /// <summary>
    /// Creates a copy of the scriptable object
    /// </summary>
    /// <typeparam name="T"> The type of the scriptable object </typeparam>
    /// <returns> A copy of the current Scriptable Object </returns>
    /// <exception cref="System.Exception"> if you see this error the whole project is fucked </exception>
    public virtual T CreateNonRefCopy<T>() where T : BaseScriptableObject
    {
        T copy = Instantiate((T)this);

        if (copy == null)
        {
            throw new System.Exception("Something went turbo wrong - " +
                "attempted to make a copy of myself but i dont exist?");
        }

        return copy;
    }
}
